---
- name: wassim-playbook
  hosts: localhost
  remote_user: root
  become: true
  tasks:

    - name: Run sonarQube contanier
      command: docker start 5e188bf6a8f4 
      ignore_errors: yes
   
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"